apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dummy.fullname" . }}
  labels:
    {{- include "dummy.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "dummy.SpecselectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dummy.PodselectorLabels" . | nindent 8 }}
      annotations:
        loki.grafana.com/format: "json"
        loki.grafana.com/drop-probes: "true"
    spec:
      serviceAccountName: dummy
      securityContext:
        runAsUser: 1000
      terminationGracePeriodSeconds: 60
      containers:
        - name: dummy
          image: "crccheck/hello-world:latest"
          ports:
            - containerPort: 8000

